name: Update requirement issue status in the general project

on:
  issues:
    types: [edited, updateProjectV2ItemFieldValue]

jobs:
  update_status:
    runs-on: ubuntu-latest
    steps:
      ##################################### PRUEBA GRAPHQL API
      - name: Checkout
        uses: actions/checkout@v2
      - name: Listar proyectos
        uses: actions/github-script@v6
        with:
          script: |
            const query = `query { organization(login: \"aequitas-aod\") { projectsV2(first: 100) { nodes { id title url repositories(first: 100){ nodes { id name }}}}}}`;
            const result = await github.graphql(query);
            console.log(result.organization.projects.nodes);
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
